### ISSUE TITLE
Sort event is not working properly

### ISSUE THREAD

**Issue by SyedMuhammadYasir** [akgulebubekir/Xamarin.Forms.DataGrid#25] opened 2017-02-20 07:56 UTC
I have bind a list with a datatime column, sort event is not working correct on that particular column. I have attach a screen shot.
![image](https://cloud.githubusercontent.com/assets/25895840/23116360/018baa90-f76c-11e6-94e5-3c3989a3a956.png)

**Comment by akgulebubekir** [comment] 2017-02-20 09:52
Hi,

it seems sorted correctly by descending. I couldn't get the issue that you've been faced.  Could you please explain detailed?

**Comment by akgulebubekir** [comment] 2017-02-23 08:32
Closing this thread. Not a bug @SyedMuhammadYasir

**Closed as completed by akgulebubekir** 2017-02-23 08:32 UTC
Labels: wontfix
